name: safe_kid_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  avatar_glow: ^2.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/aleydon.jpg
    - assets/fundo.jpg




  uses-material-design: true


